name-template: 'v$RESOLVED_VERSION 📦'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    label: 'chore'
change-template: '- #$NUMBER $TITLE (@$AUTHOR)'
version-resolver:
  major:
    labels:
      - 'release/major'
  minor:
    labels:
      - 'release/minor'
  patch:
    labels:
      - 'release/patch'
  default: patch
template: |
  ## What's new

  $CHANGES
