name: 'Automatically add issue to project'

on:
  issues:
    types: [opened]

jobs:
  add-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Add Backlog Project
      id: findColumnsByProjectName
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        query: '
          query($owner: String!, $name: String!, $search: String!) {
            repository(owner: $owner, name: $name) {
              name
              projects(first: 5, search: $search) {
                edges {
                  cursor
                  node {
                    id
                    url
                    name
                    columns(first: 10) {
                        edges {
                          cursor
                          node {
                            id
                            name
                          }
                        }
                    }
                  }
                }
              }
            }
          }
        '
        projectName: Backlog
        script: |
          const variables = {
            owner: context.repo.owner,
            name: context.repo.repo,
            search: core.getInput('projectName')
          }
          console.log(variables)
          const result = await github.graphql(core.getInput('query'), variables)
          if (!result) {
            console.log("result", result)
            core.setFailed('GraphQL request failed')
          } else {
            console.log("result", result)
            return result
          }
    - name: logging projects
      id: echoProjects
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        columnName: "To do"
        query: '
          mutation($contentId: ID!, $projectColumnId: ID!) {
            addProjectCard(input: { contentId: $contentId, projectColumnId: $projectColumnId }) {
              clientMutationId
            }
          }
        '
        projects: ${{ steps.findColumnsByProjectName.outputs.result }}
        script: |
          const findColumnsByProjectName = JSON.parse(core.getInput('projects'))
          console.log(findColumnsByProjectName)
          let columnId;
          for (const project of findColumnsByProjectName.repository.projects.edges) {
            console.log(project)
            console.log(project.node)
            console.log(project.node.columns)
            for (const column of project.node.columns.edges) {
              console.log(column)
              if (column.name == core.getInput('columnName')) {
                columnId = column.id
                return
              }
            }
          }
          const issue = context.payload.issue
          console.log("issue", issue)
          const variables = {
            contentId: issue.node_id,
            projectColumnId: columnId,
          }
          const result = await github.graphql(core.getInput('query'), variables)
          if (!result) {
            core.setFailed('GraphQL request failed')
          } 
