name: Draft Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  channel: C01DC7NL1QU

jobs:
  update_release_draft:
    name: Update release draft
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        id: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
