name: bot-wed

on:
  push:
    branches:
      - "schedules"
  schedule:
    - cron: "0 3 * * 3" # JST 12:00 (Mon)

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Run go
        run: |
          set -xe
          go run . -webhook ${{ secrets.SLACK_WEBHOOK }} -message "This is a mrkdwn section block :ghost: *this is bold*, and ~this is crossed out~, and <https://google.com|this is a link"
